import { NextResponse } from "next/server"

const propertyDetails = {
  "1": {
    id: "1",
    title: "Modern Family Home",
    price: "$450,000",
    beds: 4,
    baths: 3,
    sqft: "2,800 sq ft",
    location: "Highland Park",
    images: [
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=80",
    ],
    type: "house",
    featured: true,
    description:
      "This stunning modern family home offers the perfect blend of contemporary design and comfortable living. Located in the desirable Highland Park neighborhood, this property features an open-concept layout with high ceilings, large windows that flood the space with natural light, and premium finishes throughout. The gourmet kitchen boasts stainless steel appliances, granite countertops, and a large island perfect for entertaining. The master suite includes a walk-in closet and spa-like bathroom. The beautifully landscaped backyard provides a private oasis with mature trees and space for outdoor activities.",
    features: [
      "Open concept living",
      "Gourmet kitchen with granite countertops",
      "Master suite with walk-in closet",
      "Hardwood floors throughout",
      "Central air conditioning",
      "Two-car garage",
      "Landscaped backyard",
      "Stainless steel appliances",
      "High ceilings",
      "Large windows",
      "Premium finishes",
      "Quiet neighborhood",
    ],
    yearBuilt: 2018,
    parking: 2,
    lotSize: "0.25 acres",
    propertyType: "Single Family Home",
    status: "For Sale",
    virtualTourLink: "https://www.youtube.com/embed/vaq9B-0oBqE?autoplay=1",
    agent: {
      name: "Sarah Johnson",
      phone: "(555) 123-4567",
      email: "sarah.johnson@anantarealty.com",
      image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&h=150",
    },
  },
  "2": {
    id: "2",
    title: "Luxury Condo",
    price: "$320,000",
    beds: 2,
    baths: 2,
    sqft: "1,400 sq ft",
    location: "Downtown",
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
    ],
    type: "condo",
    featured: true,
    description:
      "Experience luxury living in this sophisticated downtown condo. This beautifully appointed 2-bedroom, 2-bathroom unit offers stunning city views and modern amenities. The open floor plan seamlessly connects the living, dining, and kitchen areas, creating an ideal space for both relaxation and entertainment. Floor-to-ceiling windows provide abundant natural light and showcase breathtaking urban vistas. The building features world-class amenities including a fitness center, rooftop terrace, and concierge service.",
    features: [
      "City views",
      "Floor-to-ceiling windows",
      "Modern kitchen with island",
      "In-unit laundry",
      "Balcony",
      "Fitness center access",
      "Rooftop terrace",
      "Concierge service",
      "Secure parking",
      "Storage unit included",
      "Pet-friendly building",
      "Walking distance to restaurants",
    ],
    yearBuilt: 2020,
    parking: 1,
    lotSize: "N/A",
    propertyType: "Condominium",
    status: "For Sale",
    virtualTourLink: "https://www.youtube.com/embed/vSvr0zl88KY?autoplay=1",
    agent: {
      name: "Michael Chen",
      phone: "(555) 234-5678",
      email: "michael.chen@anantarealty.com",
      image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&h=150",
    },
  },
  "3": {
    id: "3",
    title: "Cozy Townhouse",
    price: "$280,000",
    beds: 3,
    baths: 2,
    sqft: "1,800 sq ft",
    location: "Riverside",
    images: [
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80",
    ],
    type: "townhouse",
    featured: true,
    description:
      "This charming townhouse in the peaceful Riverside community offers comfortable family living with modern conveniences. The three-story layout provides excellent separation of living spaces, with the main level featuring an open kitchen and living area perfect for daily life and entertaining. The upper level houses the bedrooms, while the lower level offers additional flexible space. The private patio and small garden provide outdoor enjoyment in a low-maintenance setting.",
    features: [
      "Three-story layout",
      "Open kitchen and living area",
      "Private patio",
      "Small garden",
      "Attached garage",
      "Updated bathrooms",
      "Laminate flooring",
      "Energy-efficient windows",
      "Central heating",
      "Quiet community",
      "Close to schools",
      "Easy highway access",
    ],
    yearBuilt: 2015,
    parking: 1,
    lotSize: "0.05 acres",
    propertyType: "Townhouse",
    status: "For Sale",
    agent: {
      name: "Emily Rodriguez",
      phone: "(555) 345-6789",
      email: "emily.rodriguez@anantarealty.com",
      image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&h=150",
    },
  },
  "4": {
    id: "4",
    title: "Luxury Villa",
    price: "$650,000",
    beds: 5,
    baths: 4,
    sqft: "4,200 sq ft",
    location: "Beverly Hills",
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80",
    ],
    type: "luxury",
    featured: true,
    description:
      "Indulge in the epitome of luxury living with this magnificent villa in prestigious Beverly Hills. This architectural masterpiece combines elegance, comfort, and cutting-edge technology to create an unparalleled living experience. The grand foyer welcomes you into a world of sophistication, with soaring ceilings, marble floors, and custom millwork throughout. The gourmet kitchen features top-of-the-line appliances and a butler's pantry. The master suite is a private retreat with a fireplace, sitting area, and spa-like bathroom. The resort-style backyard includes a pool, spa, and outdoor kitchen.",
    features: [
      "Grand foyer with marble floors",
      "Gourmet kitchen with butler's pantry",
      "Master suite with fireplace",
      "Resort-style backyard",
      "Swimming pool and spa",
      "Outdoor kitchen",
      "Home theater",
      "Wine cellar",
      "Three-car garage",
      "Smart home technology",
      "Security system",
      "Manicured gardens",
      "Mountain views",
      "Premium location",
    ],
    yearBuilt: 2019,
    parking: 3,
    lotSize: "0.75 acres",
    propertyType: "Luxury Villa",
    status: "For Sale",
    virtualTourLink: "https://www.youtube.com/embed/-PZsSWwc9xA?autoplay=1",
    agent: {
      name: "David Thompson",
      phone: "(555) 456-7890",
      email: "david.thompson@anantarealty.com",
      image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&h=150",
    },
  },
  "5": {
    id: "5",
    title: "Luxury Waterfront Villa",
    price: "$750,000",
    beds: 5,
    baths: 4,
    sqft: "5,200 sq ft",
    location: "Beverly Hills",
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80",
    ],
    type: "luxury",
    featured: false,
    description:
      "Experience waterfront luxury at its finest in this stunning villa with panoramic water views. This exceptional property offers the perfect blend of indoor and outdoor living, with expansive terraces and floor-to-ceiling windows that showcase the breathtaking scenery. The open-concept design creates seamless flow between living spaces, while premium finishes and high-end appliances ensure the utmost in comfort and style.",
    features: [
      "Waterfront location",
      "Panoramic water views",
      "Infinity pool",
      "Private dock",
      "Outdoor entertaining areas",
      "Gourmet kitchen",
      "Wine storage",
      "Home office",
      "Guest suite",
      "Elevator",
      "Smart home features",
      "Landscaped grounds",
    ],
    yearBuilt: 2021,
    parking: 3,
    lotSize: "1.2 acres",
    propertyType: "Waterfront Villa",
    status: "For Sale",
    agent: {
      name: "Lisa Wang",
      phone: "(555) 567-8901",
      email: "lisa.wang@anantarealty.com",
      image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&h=150",
    },
  },
  "6": {
    id: "6",
    title: "Mountain Retreat Cabin",
    price: "$550,000",
    beds: 3,
    baths: 2,
    sqft: "2,400 sq ft",
    location: "Mountain View",
    images: [
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80",
    ],
    type: "luxury",
    featured: false,
    description:
      "Escape to this serene mountain retreat cabin that offers the perfect blend of rustic charm and modern amenities. Nestled among towering trees with stunning mountain views, this property provides a peaceful sanctuary away from the hustle and bustle of city life. The cabin features a cozy stone fireplace, vaulted ceilings with exposed beams, and large windows that bring the outdoors in.",
    features: [
      "Mountain views",
      "Stone fireplace",
      "Vaulted ceilings",
      "Exposed beams",
      "Wrap-around deck",
      "Hot tub",
      "Fire pit area",
      "Hiking trails nearby",
      "Updated kitchen",
      "Rustic charm",
      "Peaceful setting",
      "Wildlife viewing",
    ],
    yearBuilt: 2016,
    parking: 2,
    lotSize: "2.5 acres",
    propertyType: "Mountain Cabin",
    status: "For Sale",
    agent: {
      name: "Robert Miller",
      phone: "(555) 678-9012",
      email: "robert.miller@anantarealty.com",
      image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=150&h=150",
    },
  },
}

export async function GET(request: Request, { params }: { params: { id: string } }) {
  const { id } = params

  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 1000))

  const property = propertyDetails[id as keyof typeof propertyDetails]

  if (!property) {
    return NextResponse.json({ error: "Property not found" }, { status: 404 })
  }

  return NextResponse.json(property)
}
